import math

# SCREEN SETTINGS
RES = WIDTH, HEIGHT = 1600, 900
FPS = 60

# PLAYER SETTINGS
PLAYER_POS = 1.5, 5
PLAYER_ANG = 0
PLAYER_SPD = 0.004
PLAYER_ROT = 0.002

# FOV & RAYCAST SETTINGS
FOV = math.pi / 3
NUM_RAYS = WIDTH // 2
DELTA_ANG = FOV / NUM_RAYS
MAX_DEPTH = 20

SCREEN_DIST = (WIDTH // 2 ) / (math.tan(FOV/2))
SCALE = WIDTH // NUM_RAYS